//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIRPLAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AIRPLAN()
        {
            this.FLIGHTS = new HashSet<FLIGHT>();
        }
    
        public int ID_A { get; set; }
        public string NAME_A { get; set; }
        public string MODEL { get; set; }
        public Nullable<int> ID_AP { get; set; }
        public Nullable<int> ID_P { get; set; }
    
        public virtual AIRPORT AIRPORT { get; set; }
        public virtual PILOT PILOT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FLIGHT> FLIGHTS { get; set; }
    }
}
