//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLIGHT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FLIGHT()
        {
            this.PASSENGER1 = new HashSet<PASSENGER1>();
        }
    
        public int ID_F { get; set; }
        public Nullable<int> ID_A { get; set; }
        public Nullable<System.DateTime> DATE_D { get; set; }
        public Nullable<System.DateTime> DATE_A { get; set; }
    
        public virtual AIRPLAN AIRPLAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PASSENGER1> PASSENGER1 { get; set; }
    }
}
