//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AIRPROTEntities : DbContext
    {
        public AIRPROTEntities()
            : base("name=AIRPROTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMINLOG_> ADMINLOG_ { get; set; }
        public virtual DbSet<AIRPLAN> AIRPLANs { get; set; }
        public virtual DbSet<AIRPORT> AIRPORTs { get; set; }
        public virtual DbSet<PASSENGER1> PASSENGER1 { get; set; }
        public virtual DbSet<PILOT> PILOTS { get; set; }
        public virtual DbSet<FLIGHT> FLIGHTS { get; set; }
    }
}
