//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport
{
    using System;
    using System.Collections.Generic;
    
    public partial class PILOT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PILOT()
        {
            this.AIRPLANs = new HashSet<AIRPLAN>();
        }
    
        public int ID_P { get; set; }
        public string NAME_F { get; set; }
        public string NAME_L { get; set; }
        public Nullable<System.DateTime> DOF { get; set; }
        public Nullable<System.DateTime> EMPDATE { get; set; }
        public Nullable<int> ID_AP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AIRPLAN> AIRPLANs { get; set; }
        public virtual AIRPORT AIRPORT { get; set; }
    }
}
